### ISSUE TITLE
cmakelist doesnt exist

### ISSUE THREAD

**Issue by yaseenyahya** [maxieds/HomeBrewLiveStreamer#1]
cmakelists doesnt exist for external native

**Comment by maxieds** [comment]
@yaseenayahya : 
This is the CMakeLists.txt I have for the project. It should just be the same as the standard one generated by Android Studio for all projects since I haven't actually done anything in native / C++ in the project. At any rate, here you go: [CMakeLists.txt](https://github.com/maxieds/HomeBrewLiveStreamer/files/2197024/CMakeLists.txt)

Does it compile for you now?

**Comment by maxieds** [comment]
I also committed the CMakeLists.txt into the GitHub repo in case anyone else runs into this problem compiling with Android Studio.
